# Generated by Django 2.0.5 on 2020-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200524_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
