# Generated by Django 2.0.5 on 2020-05-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_questionmodel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='number',
        ),
    ]
