# Generated by Django 2.0.5 on 2020-05-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200525_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='tags',
            field=models.CharField(max_length=200),
        ),
    ]
