# Generated by Django 2.0.5 on 2020-05-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200527_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='tags',
            field=models.CharField(max_length=10),
        ),
    ]
